version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    expose:
      - '8081'
  redis:
    build:
      dockerfile: ./redis.Dockerfile
      context: ./
      args:
        - REDIS_PASS
    expose:
      - '6379'
  auth:
    build:
      dockerfile: music-auth.Dockerfile
      context: ./
      args:
        - REDIS_PASS
        - MONGO_PASSWORD
        - MONGO_USERNAME
    depends_on:
      - mongo
      - redis
    ports:
      - '3001:3001'
    environment:
      DB_NAME: ${AUTH_DB_NAME}
      DB_HOST: mongo
      DB_PORT: 8081
  service:
    build:
      dockerfile: ./music-service.Dockerfile
      context: ./
      args:
        - REDIS_PASS
        - MONGO_PASSWORD
        - MONGO_USERNAME
    depends_on:
      - mongo
      - redis
    ports:
      - '3000:3000'
    environment:
      DB_NAME: ${SERVICE_DB_NAME}
      DB_HOST: mongo
      DB_PORT: 8081
