name: music-api-provisioning
run-name: run terraform provisioning

on:
  push:
    branches:
      - master

jobs:
  provisioning:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: terraform format
        id: fmt
        run: terraform fmt -check

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform plan
        id: plan
        run: terraform plan -no-color

      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve
